import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import githublogo from "/public/githublogo.png"

export default function Home() {
  return (
    <div className={styles.container} style={{fontSize: "30px", }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Jay.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by contacting me @{' '}
          <code className={styles.code}>jgdodia09@gmail.com</code>
          <br />
          <br />
          Or get to know more about me @{' '}
          <code className={styles.code}><a href="https://jaysheeldodia.web.app">jaysheeldodia.web.app</a></code>
        </p>

        <p>
        <a
          href="https://github.com"
          target="_blank"
          rel="noopener noreferrer"
          style={{margin: "auto",}}
        >
          Powered By
        </a>
        
        </p>
        <a
          href="https://github.com"
          target="_blank"
          rel="noopener noreferrer"
        >
        <span className={styles.logo}>
            <Image 
              src={githublogo}
              alt="Github Logo" 
              width={120} 
              height={68} 
              style={{margin: "auto"}} 
            />
          </span>

          </a>
        
      </main>
    </div>
  )
}
